### ISSUE TITLE
No Cache Files created

### ISSUE THREAD

**Issue by garv3** [novafacile/novagallery#15]
The system does create the cache folders but no subfolders ("400x400" for example) or any cached images.
The thumbnails are not shown and only the images themselves work when opened.

Apache2 server running PHP 8 with GD support and Exif enabled.

Why does the system not create any thumbnails?

**Comment by david-novafacile** [comment]
What kind of webhosting do you use? Webhosting provider or own server?

Is it possible to open the albums (with the missing thumbnails)?

Is novaGallery installed with an own (sub)domain or in a subfolder of a (sub)domain?

Is htaccess configuration enabled and set?

**Comment by PolloEnCubitos** [comment]
Same problem here,

Using Nxing, I cant open the albums mission thumbails, installed directly on the nginx html folder and deleting the default stuff
My own server

**Comment by PolloEnCubitos** [comment]
Also happens with apache

**Comment by david-novafacile** [comment]
Hi,

this is almost the same issue on self installed server:  Not complete installed server setup for using php with common features. 

On Apache missing:
- mod rewrite
- htaccess support

Same on nginx, but there you need to set the rewrite settings in config (depending on your setup) because nginx doesn't support htaccess. Here an example for a possible configuration: https://github.com/novafacile/novagallery/issues/12#issuecomment-1144038615

Sometimes it's an permissions issue. PHP/Apache/nginx must have the rights to write in the gallery folder. Usually everything there is owned by www-data and php/apache/nginx are running with www-data. But this depends on your personal server setup and requirements.

**Comment by PolloEnCubitos** [comment]
Already do that and nothing tho, im using aarch64 processor so idk if sometimes of the php changes

**Comment by david-novafacile** [comment]
I'm sorry but I can't test this server configuration. Maybe it's an permission setting:

After adding/uploading an album. How is the owner of the directory of the album?

Maybe your system is a bit more restricted. You can try this:

Cange in `/nova-base/lib/Image.php`  the dir permission on line 150 to 0775 or 0755. Maybe 0777 ist to "open" for your server configuration

Change
https://github.com/novafacile/novagallery/blob/15b6e93c90e44994bd3da05f979d087ad38ce82b/src/nova-base/lib/Image.php#L150

to

`mkdir(self::$cacheDir, 0775, true); `

If this doesn't help:

Is it possible to use an other php script, that uses mod rewrite and file writing rights? E.g. Bludit CMS?

Which PHP 8 version do you use?

**Comment by david-novafacile** [comment]
seems to be solved...
