### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by rfcrum** [novafacile/novagallery#16]
Need help with how to set URL in site.php.  Keep getting message about site can't be reached...check if there is a typo in https.  Can somebody please provide a sample URL entry?  

Currently my entry looks like: "url": "https://xxxxxxx.a2hosted.com/public_html/novagallery/" because I've installed Novagallery in the novagallery subdirectory of my public_html page.

Or suggest what else I should look at?

Thank you!

**Comment by david-novafacile** [comment]
It depends on your host. I think the URL should be `https://xxxxxxx.a2hosted.com/novagallery/`
because `public_html` looks like the directory is where the domain points to.

Remember, if you install novaGallery in a subdir you have to modify the RewriteBase in the .htaccess file

With the example above it should be

`RewriteBase /novagallery/`

**Comment by rfcrum** [comment]
Thanks David!  I did get it to work.

 

Ross
