### ISSUE TITLE
installed fine but images/albums don't appear

### ISSUE THREAD

**Issue by dchmelik** [novafacile/novagallery#4]
I installed novaGallery at my [homesite](http://davidchmelik.com/novagallery): it says novaGallery, and my site name, fine.  I copied art into galleries/ .  However albums say 404.  I don't use .htaccess (I'm administrator) rather than main configuration (so don't know I need RewriteBase or what it is.)  It's only an Arm CPU server so might take long to generate thumbnails, but I might move to a x86 CPU server.

**Comment by david-novafacile** [comment]
Wich kind of webserver do you use? Apache2, nginx or other?

It's required to config the rewrite rules, because every request has to be handled by the index.php in root directory.

For Apache2 this can be configured in the .htaccess file (file is included). For other webserver you must set this in the server config.

This is the same principle and behavior as with any other PHP software (e.g. like Wordpress, Nextcloud).

If you install the gallery in a subfolder of a domain (e.g. mydomain.com/novagallery/), you have to set this as RewriteBase in .htaccess

Example:
`RewriteBase /novagallery`

If you install it on root Domain (e.g. mydomain.com) than it's only `RewriteBase /`.

Does that help or are you using a web server other than Apache. For nginx I can also provide you with a possible configuration, but then you have to adapt it to your personal config.

It doesn't matter if you have an ARM or X86 CPU. The webserver config is important.

**Comment by dchmelik** [comment]
I admit I use Apache (might change to something else later) but don't know much/anything about mod_rewrite.  Once I installed Mediawiki but just copied & pasted  from MediaWiki.org instructions.

I put RewriteBase in the virtual host (vhost; ) this is some of it.
```
    ServerName davidchmelik.com
    ServerAlias www.davidchmelik.com
    RewriteBase /novagallery
```
There are no more rewrite commands, and It's not the front page but embedded, and accessed full-page davidchmelik.com/novagallery .

**Comment by david-novafacile** [comment]
It really looks like missing ModRewrite configuration.

Unfortunately I am not an expert in Apache configuration either. The easiest way would be to enable in your vhost the possibility to use .htaccess and the mod_rewrite module.

Then you can use any PHP software that uses .htaccess for configuration. This is usually also standard, unless you explicitly don't want to do that for certain reasons and want to set everything individually in the vhosts.

**Comment by david-novafacile** [comment]
Maybe this helps:

Enable .htaccess
https://webrewrite.com/enable-htaccess-file-apache2/

Enable mod_rewrite and use htaccess:
https://stackoverflow.com/a/5758551

**Comment by dchmelik** [comment]
Perhaps was because I worked on this late at night, I didn't notice everything and got a bit confused.  I see novaGallery already has its own .htaccess file, but for some reason I thought the command was supposed to go somewhere in my own main Apache configuration, how I usually do things.  So, I just enabled .htaccess, updated that line, and now it's working! :D
