### ISSUE TITLE
Very nice web ui for sharing home photos, do you know something similar for videos too?

### ISSUE THREAD

**Issue by muniv11111** [novafacile/novagallery#8]
Thank you for the excellent work ...

I found a small bug when there are two empty albums in path and then there are pictures in the next album, so the paths to them are somehow poorly indexed. When I removed the empty albums in the path, everything is fine. I don't know at all if I would be able to replicate it accurately though.
So just a question from the headline: does anyone know of a similar piece for video sharing? Or would it be difficult or bold to ask to improve novagallery with this feature? :-)

**Comment by david-novafacile** [comment]
I will check the empty album bug. Thanks for reporting. :-)

Currently video sharing isn't planned, because good video sharing requires some more specials and a youtube or vimeo integration requieres something like an admin interface. These features are explicitly not implemented to make novaGallery work as simple as possible.

A simple plugin system is planned for the next major release. This would make it easier to extend novaGallery with such features. But this will take quite a while until the new major release.
